### ISSUE TITLE
Variant side panel - Reviewed filter count

### ISSUE THREAD

**Issue by mvelinder** [iobio/gene.iobio.vue#374]
From Al - If a variant is assigned Not significant or poor quality, it doesn’t count as reviewed, but it has been reviewed

**Comment by AlistairNWard** [comment]
@tonydisera @mvelinder @WilliamRichards2017 This is technically fixed, but not desirable. If I assign a significance, I have to click on something elsewhere to update the side panel. Selecting the term should trigger the variant side panel update. I thought this wasn't fixed since nothing happened when I assigned a significance
