### ISSUE TITLE
Kick off analyze gene coverage from CoverageSettings dialog

### ISSUE THREAD

**Issue by mvelinder** [iobio/gene.iobio.vue#377]
Need a way to kick off 'analyze gene coverage' from new Coverage Settings dialog.  (Used to be accomplished by 'Analyze all' button).

**Comment by tonydisera** [comment]
I think we can hold off on this until after release 4.0.  Are you okay with that @mvelinder @AlistairNWard ?  If the cutoffs are set in the 'Insufficient Coverage' popup, it seems like the genes are getting refreshed properly to show exons that don't meet the coverage min, mean, and median. .

**Comment by AlistairNWard** [comment]
Just so I'm clear, this means I click Assess Coverage from the menu bar?

If I go into this and change the settings, then click Apply, the hover over an exon will show the new values, but the exons themselves aren't flagged, and the count of genes that have exons failing coverage (e.g. in the left panel, and in the menu bar in the Assess Coverage button) does not update. It seems like we would have to have these update, otherwise someone applying more stringent coverage rules would not realise that some exons now fail unless they go through every gene and hover over the exon.

If I'm understanding the issue correctly, I would say the updating has to work for this to available. But we could just make it so the user can't edit the values for now, rather than fixing

**Comment by tonydisera** [comment]
Damn it.  Is this broken?

**Comment by mvelinder** [comment]
I'm not super clear what the issue is here. Sounds like we're talking about two different things?

**Comment by AlistairNWard** [comment]
@mvelinder I was just guessing. I have no idea what CoverageSettings is referring to, and this was my best guess!

**Comment by tonydisera** [comment]
Sorry.  Will is working on this issue.  Basically, if you click on the 'Assess Coverage' in the nav bar and change the cutoffs and press 'Apply', the app is supposed to automatically review the coverage in the exons to see if any should be highlighted as 'insufficient coverage'.  This appears to have some quirks right now, so the functionality isn't quite there.
