### ISSUE TITLE
Investigage strange multi-allelic 18-03-03_ARUP-Marth-Hypomyelinating_Leukodystrophy

### ISSUE THREAD

**Issue by mvelinder** [iobio/gene.iobio.vue#378]
![image](https://user-images.githubusercontent.com/22081541/76560675-4f1e0d00-6467-11ea-96f3-ee1672ae7432.png)

**Comment by AlistairNWard** [comment]
This issue is a good test case for streamlining the command line used to parse the vcf file. This shouldn't be multiallelic. I used the command at the end of this issue on the vcf file (with GRCh37 ref), to see what this variant looks like, and got the following:

`3       160142810       .       A       ATGTGTGTGTGTGTG 218621  PASS    .       GT:AD:DP:GQ:PGT:PID     1/1:0,0,0,0,17,0,0,0,0,0,0,0,0,0:17:54:.:.      0/0:23,0,0,0,0,0,0,0,0,0,0,0,0,0:23:11:.:.      0/1:3,2,0,0,5,0,0,0,0,0,0,0,0,0:10:30:.:.`

The original record (which is multiallelic) is below, but for the samples in this family, they all share the same alternate (which was the 4th alternate in the original record).

`3	160142810	.	ATGTGTGTGTGTG	ATGTGTGTGTG,ATGTGTGTGTGTGTGTGTGTGTGTG,ATGTGTGTGTGTGTGTGTGTG,ATGTGTGTGTGTGTGTGTGTGTGTGTG,ATGTGTGTGTGTGTGTGTGTGTG,A,ATG,ATGTGTGTGTGTGTGTGTGTGTGTGTGTGTG,ATGTGTGTGTGTGTGTGTGTGTGTGTGTG,ATGTGTGTGTGTGTG,ATGTGTGTGTGTGTGTG,ATGTGTGTGTGTGTGTGTG,GTGTGTGTGTGTG	218621	PASS	AC=0,0,0,3,0,0,0,0,0,0,0,0,0;AN=6	GT:AD:DP:GQ:PGT:PID	4/4:0,0,0,0,17,0,0,0,0,0,0,0,0,0:17:54:.:.	0/0:23,0,0,0,0,0,0,0,0,0,0,0,0,0:23:11:.:.	0/4:3,2,0,0,5,0,0,0,0,0,0,0,0,0:10:30:.:.`

`VCF=/scratch/ucgd/lustre/UCGD_Datahub/Repository/AnalysisData/2018/A534/18-03-03_ARUP-Marth-Hypomyelinating_Leukodystrophy/UCGD/GRCh37/VCF/Complete/18-03-03_ARUP-Marth-Hypomyelinating_Leukodystrophy_Final_1520190734.vcf.gz
bcftools view $VCF 3:160142810-160142810 | 
bcftools norm -m - -w 10000 -f $FASTA | 
bcftools view -s 16147400612,16147400619,16147400616 -a -c 1 | 
less`
