### ISSUE TITLE
Chrome shows 'not secure' when running https://gene.iobio.io

### ISSUE THREAD

**Issue by tonydisera** [iobio/gene.iobio.vue#471]
<img width="973" alt="Screen Shot 2020-04-16 at 8 10 15 PM" src="https://user-images.githubusercontent.com/8420103/79524726-79428c00-801e-11ea-9823-2f98d036d897.png">

**Comment by anderspitman** [comment]
Same in firefox. The reason is that some of the requests are being made over http. For example, `http://iobio.io/public/images/blog/gene_3.0/banner.png`. In order to fix that we'll need to get iobio.io working on https, which we've needed to fix for a while anyway.

You can see all the insecure requests in the network tab when you run gene.

**Comment by AlistairNWard** [comment]
If this is still outstanding, then it looks like something we need to address.

**Comment by mvelinder** [comment]
Looks fixed to me 
![image](https://user-images.githubusercontent.com/22081541/99542543-71114d00-296f-11eb-94b2-e93d7cdbd9e2.png)

**Comment by mvelinder** [comment]
![image](https://user-images.githubusercontent.com/22081541/102253758-faf7fb80-3ec4-11eb-9895-44222c21d62f.png)
in Firefox

**Comment by mvelinder** [comment]
Looks fixed, why reopen?

**Comment by AlistairNWard** [comment]
Because it still shows as not secure on Firefox

**Comment by mvelinder** [comment]
Making a new issue for Firefox specifically so we don't have to follow the thread and be misled by the issue title
