### ISSUE TITLE
Add internal endpoints 

### ISSUE THREAD

**Issue by tonydisera** [iobio/gene.iobio.vue#522]
From Chase:
I'll link the full instructions for all iobio apps here https://marthlab.slack.com/archives/C010YCELHEC/p1587048413038100
But for gene specifically, there are only two changes needed

1. Change any API requests to mosaic from /apiv1/ to /api/v1/. I believe there is only 1 apiv1/user

2. Gene.iobio currently uses apiv1/client-applications to get the client application ID. The client-application ID is also in the URL, so the fix here is to stop using the endpoint above and instead grab the ID from the URL params.

**Comment by stefinfection** [comment]
For documentation purposes: this change was implemented and deployed to production in cohort-gene also, but because as of June 2020, the files associated with projects cohort needs to function do not currently exist in Utah Mosaic, this is untested. Will circle back once there are actual files to test with. Until then, cohort is hidden from users in Utah Mosaic.

**Comment by AlistairNWard** [comment]
@tonydisera Are the endpoints correct now?

**Comment by anderspitman** [comment]
I believe @adityaekawade recently updated some endpoints as well.
