### ISSUE TITLE
Exon with no coverage isn't flagged

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/gene.iobio.vue#564]
Mosaic project 111 (A469). From Analyses, launch CNGA1 gene paper analysis.

![Screen Shot 2020-07-23 at 4 32 12 PM](https://user-images.githubusercontent.com/523111/88335914-14c05880-cd02-11ea-8ed2-b428c4258e68.png)

I am hovering over exon 1 which appears to have no coverage at all, but only exon 2 is flagged as having low coverage. The summary also states that there is only 1 exon with insufficient coverage. There should be 2.

**Comment by AlistairNWard** [comment]
@tonydisera Do we just not look at UTRs? Should we?

**Comment by mvelinder** [comment]
Good point. Some exons can be UTRs. We need to specify whether it's exons with insufficient coverage we're flagging or coding sequencing with insufficient coverage. I think we should include any exon (UTR or otherwise) that has insufficient coverage.

**Comment by AlistairNWard** [comment]
Agreed, we should include UTRs. For now it looks like an error, which we don't want users to think

**Comment by adityaekawade** [comment]
UTR's that do not have coverage should now be flagged for insufficient coverage. The summary badge will also show the count of exons with insufficient coverage. Test: http://0be71a8c.quarantest.iobio.io/

![Screen Shot 2021-08-11 at 5 57 26 PM](https://user-images.githubusercontent.com/16284713/129122214-bdaf08ce-6075-49e4-beeb-6702e6cfc117.png)

But I also noticed some exons have both UTR and CDS. In the screenshot below, you can see that exon 3 (17792933 - 17798513) is flagged for UTR (17792933 - 17792949) but also has CDS (17792949 - 17798513). 
![Screen Shot 2021-08-11 at 5 59 00 PM](https://user-images.githubusercontent.com/16284713/129122347-c29f5117-19e6-43d9-a4e4-51eac2659398.png)

As all the exons with insufficient coverage have the flagged, all the 6 genes in the demo data now show the insufficient coverage icon in the left sidebar. 
![Screen Shot 2021-08-11 at 6 06 37 PM](https://user-images.githubusercontent.com/16284713/129122812-c2616513-2ead-4081-84fe-5f6853e9af32.png)

This turned out to be a tricky issue. Let me know if this is expected behavior. 

@mvelinder @AlistairNWard

**Comment by adityaekawade** [comment]
Pushed an update that fixes the exons count.

**Comment by adityaekawade** [comment]
Use this commit history for reference: https://github.com/iobio/gene.iobio.vue/commit/0e32a4a33ba0695964e638dfbe67b973f9002ba3
