### ISSUE TITLE
When there is no pathogenic variant,  but striked-out grey circle should show the consequence. 

### ISSUE THREAD

**Issue by tonydisera** [iobio/gene.iobio.vue#566]
Dennis Grishan (Nebula) noticed that there are cases where this shows:

<img width="280" alt="Screen Shot 2020-07-23 at 6 59 45 PM" src="https://user-images.githubusercontent.com/8420103/88352355-bce01c80-cd16-11ea-90a1-5187ec42fda2.png">

Instead of this:

![Uploading Screen Shot 2020-07-23 at 6.59.49 PM.png…]()

**Comment by tonydisera** [comment]
<img width="1158" alt="Screen Shot 2020-07-23 at 9 06 50 PM" src="https://user-images.githubusercontent.com/8420103/88357433-7abfd680-cd28-11ea-8e3f-378b9a76a81e.png">

**Comment by AlistairNWard** [comment]
@tonydisera the screenshot of what is supposed to be seen is missing. I have problems with the gray icon in other places since it isn't clear what it implies. My assumption here is that the variant isn't in ClinVar because it is intronic? In cases where we just say intron variant, is it clear to a user what they are supposed to draw from that? Should we have a tooltip explaining what that means in terms of ClinVar? Or if there is no clinical significance, should we just state that there is no clinical significance?

**Comment by mvelinder** [comment]
Let's incorporate this into #628 glyph overhaul

**Comment by AlistairNWard** [comment]
The Nebula document that raised this issue didn't include a specific example to check. I looked through some whole genomes and found grayed out variants and intron variants, and couldn't see an example of this happening. The pathogenicity was either blank or included a statement that it was an intron variant
