### ISSUE TITLE
No allele count for singleton

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/gene.iobio.vue#574]
If you have a trio, the pedigree shows the allele counts for all samples. If we have a singleton, the pedigree visualization is removed, but that means there is no allele count either. We should consider keeping the pedigree visualization, since there is useful information here, even if we have a singleton or duo.

**Comment by tonydisera** [comment]
I changed some logic in gene.iobio to make sure that sex is grabbed from the pedigree so that the correct symbol shows for the singleton pedigree.  
Also, I show the label 'unknown' when single proband launched.
<img width="187" alt="Screen Shot 2020-11-21 at 10 22 45 AM" src="https://user-images.githubusercontent.com/8420103/99883832-0f5b1800-2be7-11eb-81f9-2da4faeabf87.png">

I found some pedigrees in Mosaic that didn't have parents and tested that the single node shows correctly in the pedigree/genotype viz.  However, I could not find a case where there was one parent and a proband.  It would be good to test with that use case.  @AlistairNWard @mvelinder, do you know of any 1 parent + proband cases I could test with?  Thanks!

**Comment by AlistairNWard** [comment]
This is a mother / daughter pedigree. Looks to be working.

https://mosaic.chpc.utah.edu/#/projects/54/samples/1408/pedigree

![Screen Shot 2020-11-23 at 9 10 51 AM](https://user-images.githubusercontent.com/523111/99971888-cf716d80-2d6b-11eb-8a7c-6a1affa029cd.png)

**Comment by AlistairNWard** [comment]
Yes, this is fixed.
