### ISSUE TITLE
Gene name hover over mentions phenotype

### ISSUE THREAD

**Issue by mvelinder** [iobio/gene.iobio.vue#641]
![image](https://user-images.githubusercontent.com/22081541/95473225-1da7ea00-0941-11eb-80d5-dcd228bef7d5.png)

Gene name hover over mentions phenotype, this is confusing and we should remove it for clarity that you only input a gene

**Comment by AlistairNWard** [comment]
Not sure how we haven't caught that before

**Comment by WilliamRichards2017** [comment]
This appears to be a Nebula specific error, and I'll get this taken care of as soon as I hear back about how to test gene in Nebula mode.  This information dialog pops up on page load when there are no genes or variants loaded.  There's logic in place to only display the message 'Enter a gene name' for versions that don't have a phenotype search bar, so either this logic is missing a nebula check (not sure what 'mode' nebula is), or the user who emailed Matt the
is screenshot is on an outdated version of gene with nebula.  I'll update you when I've tested on nebula and understand what the issue is

**Comment by AlistairNWard** [comment]
This appears on production gene. I just opened production, went to the files menu option and chose the WES trio. Gene opens with the following:

![Screen Shot 2020-10-08 at 1 54 38 PM](https://user-images.githubusercontent.com/523111/95495822-f0256580-096d-11eb-8a04-3216678b6e09.png)

So this isn't Nebula specific.

**Comment by WilliamRichards2017** [comment]
So the incorrect message for Nebula being displayed is only because Nebula is running on an outdated version of gene, and is already fixed on the current production version.  Tony sent a message to Frameshift and Dennis from Nebula, and we would like to coordinate a nebula update later next week.  I can still go ahead and split the single text modal into two separate text modals.

**Comment by mvelinder** [comment]
I closed this @WilliamRichards2017 , seemed finished
