### ISSUE TITLE
Change recessive R glyph to AR and change X glyph to XL

### ISSUE THREAD

**Issue by mvelinder** [iobio/gene.iobio.vue#665]
Change recessive "R" glyph to "AR" and X linked "X" glyph to "XL" to be consistent with AD

**Comment by adityaekawade** [comment]
Here is a new glyph for AR 
![Asset 1](https://user-images.githubusercontent.com/16284713/99708292-827f5580-2a52-11eb-9946-d597358e4be9.png)

@mvelinder for XL (X-linked) do you need two dots on top of the letters? If yes should it be one red and one white as you have mentioned it to be consistent with AD? 
Currently, there is only one dot over X

**Comment by tonydisera** [comment]
To test, use Platinum demo trio.  AR (recessive) will show for RAI1
<img width="150" alt="Screen Shot 2020-11-20 at 6 38 48 PM" src="https://user-images.githubusercontent.com/8420103/99864319-cdd35a00-2b5f-11eb-892c-a5b36f6b4764.png">
<img width="194" alt="Screen Shot 2020-11-20 at 6 38 55 PM" src="https://user-images.githubusercontent.com/8420103/99864323-d461d180-2b5f-11eb-849d-5f9518a7c0e7.png">
<img width="201" alt="Screen Shot 2020-11-20 at 6 39 04 PM" src="https://user-images.githubusercontent.com/8420103/99864330-d88def00-2b5f-11eb-8715-ac6813ea4041.png">


.  XL (x-linked) will show for PIN4.

**Comment by mvelinder** [comment]
> Here is a new glyph for AR
> ![Asset 1](https://user-images.githubusercontent.com/16284713/99708292-827f5580-2a52-11eb-9946-d597358e4be9.png)
> 
> @mvelinder for XL (X-linked) do you need two dots on top of the letters? If yes should it be one red and one white as you have mentioned it to be consistent with AD?
> Currently, there is only one dot over X

Nope, for AR both circles should be filled red. Each circle is representing an allele, so for AR (recessive) both alleles would be alt.

**Comment by mvelinder** [comment]
> To test, use Platinum demo trio. AR (recessive) will show for RAI1. XL (x-linked) will show for PIN4.
> 
> <img alt="Screen Shot 2020-11-20 at 6 38 48 PM" width="150" src="https://user-images.githubusercontent.com/8420103/99864319-cdd35a00-2b5f-11eb-892c-a5b36f6b4764.png">
> 
> <img alt="Screen Shot 2020-11-20 at 6 38 55 PM" width="194" src="https://user-images.githubusercontent.com/8420103/99864323-d461d180-2b5f-11eb-849d-5f9518a7c0e7.png">
> 
> <img alt="Screen Shot 2020-11-20 at 6 39 04 PM" width="201" src="https://user-images.githubusercontent.com/8420103/99864330-d88def00-2b5f-11eb-8715-ac6813ea4041.png">

@tonydisera I don't think the X-linked is being properly displayed, this PIN4 variant you mentioned is not X-linked, it is just hom-alt in all samples. The logic for X-linked is not just hom-alt and on X. It needs to account for proband being male and inheriting a variant from a parent (likely mom, a hemizygous example) or for proband being female and inheriting an alt from each parent. Let me know if that makes sense.
![image](https://user-images.githubusercontent.com/22081541/100145009-e93aaf80-2e54-11eb-97d5-d26600dd26f6.png)

**Comment by AlistairNWard** [comment]
I think the question of colours is for X-linked - not AR. This is only an issue if X-linked need two dots. My understanding is that X-linked should only have one dot, and it will always be filled red.

**Comment by mvelinder** [comment]
Oh, for X-linked males the most accurate depiction would be just one dot over the X and shared red. And shaded two dots over the X for females. Do we want to make that distinction for X-linked variants in male probands?

**Comment by AlistairNWard** [comment]
I think so. It is important.

**Comment by mvelinder** [comment]
I agree, it's worth the extra work to do it correctly

**Comment by tonydisera** [comment]
Good point.  Do you mind if I create another issue and address this in the next release?  It is one of those seemingly simple fixes that I suspect will take a little bit more work.

**Comment by tonydisera** [comment]
I will double-check that indeed the code is looking for hom-alt for female probands.

**Comment by mvelinder** [comment]
Thanks @tonydisera - and hom-alt for male probands, genotype for male probands will still be 1/1

**Comment by tonydisera** [comment]
Hmm..  So I think I saw @mvelinder that you added an issue to specify sex for the proband.  So right now, we cannot tell from the genotype alone if this is X-linked female or X-linked male.  Should I still implement the logic assuming that down the road, we will know the sex of the proband?  (For Mosaic launched, we are fine).

**Comment by tonydisera** [comment]
I was able to make the fix so that this glyph shows for female probands with an x-linked inheritance.  
To test, load demo platinum trio with PIN4.  Then amp up the X-linked filter to 100% allele frequency.
<img width="654" alt="Screen Shot 2020-11-25 at 5 37 05 PM" src="https://user-images.githubusercontent.com/8420103/100294786-0a7ac900-2f45-11eb-86da-e740aa6b015a.png">

You should see the two dots above the X-linked glyph since the proband is a female.  
<img width="192" alt="Screen Shot 2020-11-25 at 5 37 19 PM" src="https://user-images.githubusercontent.com/8420103/100294841-3ac26780-2f45-11eb-93de-5e80cb69df32.png">
<img width="320" alt="Screen Shot 2020-11-25 at 5 37 37 PM" src="https://user-images.githubusercontent.com/8420103/100294844-3eee8500-2f45-11eb-8634-e82fe88864f1.png">
<img width="304" alt="Screen Shot 2020-11-25 at 5 37 46 PM" src="https://user-images.githubusercontent.com/8420103/100294851-41e97580-2f45-11eb-9347-489c685660e8.png">


When the proband's sex is male or is not known, the one dot XL glyph will show as the default.

**Comment by AlistairNWard** [comment]
I don't have the sex information apparently, as I just get the diamonds. But I do see the XL with one dot, which seems fine when we don't know the sex. I see a couple of issues on mine though:

1. The pedigree chart is messed up (on stage.gene when I picked data from the menu bar option, rather than selecting demo data on the landing page). The diamonds are shifted up, so the vertical lines pass through them. The same occurs in your screenshot Tony, but only for the male - you can see the vertical line, but it's less obvious because it's a het.

![Screen Shot 2020-11-30 at 11 37 57 AM](https://user-images.githubusercontent.com/523111/100637232-a2d7cb80-3300-11eb-8400-7247347e83c8.png)

2. The sib has no allele count (when data loaded as in step 1).

**Comment by tonydisera** [comment]
Ah!   I was wondering where that line came from. It didn't look as odd when the unaffected sib was a male.   I think I know the problematic code to fix.  Thank you!

**Comment by tonydisera** [comment]
@AlistairNWard , thanks for catching this.  You can re-test on stage.gene.iobio.io now.

**Comment by AlistairNWard** [comment]
Thanks @tonydisera , pedigree back to full strength!

Any idea why I don't see an allele count for the sib though?

**Comment by tonydisera** [comment]
@AlistairNWard, I have no idea.  I'll take a look.

**Comment by AlistairNWard** [comment]
Works for me
